# Generated by Django 5.0.2 on 2024-02-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sap', models.CharField(max_length=50)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('direccion_proyecto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemOfertaDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oferta', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ordendeventa')),
            ],
        ),
    ]
