# Generated by Django 5.0.2 on 2024-02-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ordendeventa_itemofertadeventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeventa',
            name='codigo_sap',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
