# Generated by Django 5.0.2 on 2024-02-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ordendeventa_codigo_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeventa',
            name='direccion_proyecto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='nombre_proyecto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordendeventa',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
